# RAG Service Configuration
# This file contains all configurable settings for the RAG service

# Application Settings
app:
  title: "RAG Service"
  description: "A modular Retrieval-Augmented Generation service"
  version: "1.0.0"
  host: "0.0.0.0"
  port: 8000
  debug: false

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "data/rag_service.log"
  console: true

# Data Storage Configuration
data:
  directory: "data"
  vector_index_path: "data/vector_index"
  vector_dimension: 384

# LLM Service Configuration
llm:
  model_name: "qwen3:4b"
  ollama_url: "http://localhost:11434"
  request_timeout: 30
  generation_options:
    temperature: 0.7
    top_p: 0.9
    top_k: 40
    repeat_penalty: 1.1
    num_predict: 1024

# Embedding Model Configuration
embeddings:
  model_name: "all-MiniLM-L6-v2"
  dimension: 384

# Chunking Configuration
chunking:
  default_chunk_size: 500
  default_chunk_overlap: 50
  max_chunk_size: 1000
  min_chunk_size: 100

# Crawler Configuration
crawler:
  default_max_pages: 10
  default_max_depth: 2
  default_delay_ms: 1000
  min_delay_ms: 100
  max_delay_ms: 5000
  user_agent: "RAG-Service/1.0"
  headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    Accept-Language: "en-US,en;q=0.5"
    Accept-Encoding: "gzip, deflate"
    Connection: "keep-alive"
    Upgrade-Insecure-Requests: "1"

# Q&A Service Configuration
qa:
  default_min_relevance: 0.5
  default_top_k: 5
  max_question_length: 1000
  min_question_length: 1

# Vector Store Configuration
vector_store:
  similarity_threshold: 0.95
  max_merge_distance: 2
  enable_deduplication: true


# CORS Configuration
cors:
  allow_origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]
# Development/Testing Configuration
development:
  enable_hot_reload: false
  log_level: "DEBUG"

